"attributes" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base0D"
"debug" = "base03"
"diagnostic" = { modifiers = ["underlined"] }
"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus" = "base0B"
"error" = "base08"
"function" = "base0D"
"hint" = "base03"
"info" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base0D"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string"  = "base0B"
"type" = "base0A"
"ui.background" = { bg = "base00" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = { fg = "base03" }
"ui.window" = { bg = "base01" }
"variable" = "base08"
"variable.other.member" = "base0B"
"warning" = "base09"

[palette]
base00 = "#feedf3" # Default Background
base01 = "#f8e2e7" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#e0ccd1" # Selection Background
base03 = "#755f64" # Comments, Invisibles, Line Highlighting
base04 = "#665055" # Dark Foreground (Used for status bars)
base05 = "#564448" # Default Foreground, Caret, Delimiters, Operators
base06 = "#42383a" # Light Foreground (Not often used)
base07 = "#33292b" # Light Background (Not often used)
base08 = "#df2d52" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#f6661e" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#c29461" # Classes, Markup Bold, Search Text Background
base0B = "#2e916d" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#1d8991" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#006e93" # Functions, Methods, Attribute IDs, Headings
base0E = "#5e2180" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#ba0d35" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
