# Scheme name: Measured Dark
# Scheme author: Measured (https://measured.co)
# Template author: Tinted Theming (https://github.com/tinted-theming)

"attributes" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base0D"
"debug" = "base03"
"diagnostic" = { modifiers = ["underlined"] }
"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus" = "base0B"
"error" = "base08"
"function" = "base0D"
"hint" = "base03"
"info" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string"  = "base0B"
"type" = "base0A"
"variable" = "base08"
"variable.other.member" = "base0B"
"warning" = "base09"

"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base0D"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { style = "curl" } }

"ui.background" = { bg = "base00" }
"ui.bufferline.active" = { fg = "base00", bg = "base03", modifiers = ["bold"] }
"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.cursor" = { fg = "base0A", modifiers = ["reversed"] }
"ui.cursor.insert" = { fg = "base0A", modifiers = ["reversed"] }
"ui.cursorline.primary" = { fg = "base05", bg = "base01" }
"ui.cursor.match" = { fg = "base0A", modifiers = ["reversed"] }
"ui.cursor.select" = { fg = "base0A", modifiers = ["reversed"] }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.scroll" = { fg = "base03", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.selection.primary" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.statusline.inactive" = { bg = "base01", fg = "base03" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.normal" = { fg = "base00", bg = "base03" }
"ui.statusline.select" = { fg = "base00", bg = "base0F" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.virtual.indent-guide" = { fg = "base03" }
"ui.virtual.inlay-hint" = { fg = "base03" }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.jump-label" = { fg = "base0A", modifiers = ["bold"] }
"ui.window" = { bg = "base01" }

[palette]
base00 = "#00211f" # Default Background
base01 = "#003a38" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#005453" # Selection Background
base03 = "#ababab" # Comments, Invisibles, Line Highlighting
base04 = "#c3c3c3" # Dark Foreground (Used for status bars)
base05 = "#dcdcdc" # Default Foreground, Caret, Delimiters, Operators
base06 = "#efefef" # Light Foreground (Not often used)
base07 = "#f5f5f5" # Light Background (Not often used)
base08 = "#ce7e8e" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#dca37c" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#bfac4e" # Classes, Markup Bold, Search Text Background
base0B = "#56c16f" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#62c0be" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#88b0da" # Functions, Methods, Attribute IDs, Headings
base0E = "#b39be0" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#d89aba" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
