# Scheme name: Primer Dark Dimmed
# Scheme author: Jimmy Lin
# Template author: Tinted Theming (https://github.com/tinted-theming)

"attributes" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base0D"
"debug" = "base03"
"diagnostic" = { modifiers = ["underlined"] }
"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus" = "base0B"
"error" = "base08"
"function" = "base0D"
"hint" = "base03"
"info" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string"  = "base0B"
"type" = "base0A"
"variable" = "base08"
"variable.other.member" = "base0B"
"warning" = "base09"

"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base0D"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { style = "curl" } }

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base00", bg = "base03", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "base03", bg = "base01" }
"ui.selection.primary" = { bg = "base02" }
"ui.cursor.select" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.insert" = { fg = "base0A", modifiers = ["underlined"] }
"ui.background" = { bg = "base00" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursorline.primary" = { fg = "base05", bg = "base01" }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.statusline.inactive" = { bg = "base01", fg = "base03" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.normal" = { fg = "base00", bg = "base03" }
"ui.statusline.select" = { fg = "base00", bg = "base0F" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.indent-guide" = { fg = "base03" }
"ui.virtual.whitespace" = { fg = "base01" }
"ui.window" = { bg = "base01" }

[palette]
base00 = "#1c2128" # Default Background
base01 = "#373e47" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#444c56" # Selection Background
base03 = "#545d68" # Comments, Invisibles, Line Highlighting
base04 = "#768390" # Dark Foreground (Used for status bars)
base05 = "#909dab" # Default Foreground, Caret, Delimiters, Operators
base06 = "#adbac7" # Light Foreground (Not often used)
base07 = "#cdd9e5" # Light Background (Not often used)
base08 = "#f47067" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#e0823d" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#c69026" # Classes, Markup Bold, Search Text Background
base0B = "#57ab5a" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#96d0ff" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#539bf5" # Functions, Methods, Attribute IDs, Headings
base0E = "#e275ad" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#ae5622" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
