"attributes" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base0D"
"debug" = "base03"
"diagnostic" = { modifiers = ["underlined"] }
"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus" = "base0B"
"error" = "base08"
"function" = "base0D"
"hint" = "base03"
"info" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base0D"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string"  = "base0B"
"type" = "base0A"
"ui.background" = { bg = "base00" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = { fg = "base03" }
"ui.window" = { bg = "base01" }
"variable" = "base08"
"variable.other.member" = "base0B"
"warning" = "base09"

# Mode highlighting
"ui.statusline.normal" = { fg = "base00", bg = "base03" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.select" = { fg = "base00", bg = "base0F" }

[palette]
base00 = "#231e18" # Default Background
base01 = "#302b25" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#48413a" # Selection Background
base03 = "#9d8b70" # Comments, Invisibles, Line Highlighting
base04 = "#b4a490" # Dark Foreground (Used for status bars)
base05 = "#cabcb1" # Default Foreground, Caret, Delimiters, Operators
base06 = "#d7c8bc" # Light Foreground (Not often used)
base07 = "#e4d4c8" # Light Background (Not often used)
base08 = "#d35c5c" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#ca7f32" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#e0ac16" # Classes, Markup Bold, Search Text Background
base0B = "#b7ba53" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#6eb958" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#88a4d3" # Functions, Methods, Attribute IDs, Headings
base0E = "#bb90e2" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#b49368" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
